# -*- coding: utf-8 -*-
"""Library.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VWxkwcLK19VoGfU2ANdZX_Ow1m48u4X9
"""

import os

class Library:
    def __init__(self,fileName = 'books.txt'):
        self.fileName = fileName

    def addBook(self, bookInfo):
        with open(self.fileName,'a',encoding='utf-8') as file:
            file.write(bookInfo + '\n')

    def listBooks(self):
        try:
            with open(self.fileName,'r',encoding='utf-8') as file:
                books = file.readlines()
            return [book.strip() for book in books]
        except FileNotFoundError:
          return[]

    def removeBook(self,bookName):
      updatedBooks = []
      with open(self.fileName,'r',encoding='utf-8') as file:
          books = file.readlines()
          for book in books:
              currentBookName = book.split(',')[0].strip()
              if currentBookName != bookName:
                  updatedBooks.append(book.strip())

      with open(self.fileName,'w',encoding='utf-8') as file:
        for book in updatedBooks:
         file.write(book + '\n')


library = Library('books.txt')

print("****MENU****")
print("1) List Books")
print("2) Add Books")
print("3) Remove Books")
print("q) Quit")

while True:
    choice = input("Enter your choice: ")

    if choice == '1':
        booksList = library.listBooks()
        if booksList:
            for book in booksList:
                print(book)
        else:
           print("No books found")
    elif choice == '2':
        bookName = input("Enter a book name:")
        author = input("Enter the author:")
        release_year = input("Enter the release year:")
        num_pages = input("Enter the number of pages:")
        bookInfo = f"{bookName},{author},{release_year},{num_pages}"
        library.addBook(bookInfo)
        print(f"'{bookName}' added")
    elif choice == '3':
        bookName = input("Enter a bookname delete for list:")
        library.removeBook(bookName)
        print(f"'{bookName}' deleted")
    elif choice.lower() == "q":
      break
    else:
        print("Invalid Choice")